/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Compras
 * OpenAPI spec version: 1.0.0
 */

export interface AgregarProductoCompraSchema {
  producto_id: number;
  pedido_producto_id?: number | null;
  cantidad?: number | null;
  unidad_medida?: string | null;
  precio_de_compra: number;
  ganancia_deseada?: number | null;
  estado_compra?: 'comprado' | 'no_comprado' | null;
  motivo_no_compra?: string | null;
}
