/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Compras
 * OpenAPI spec version: 1.0.0
 */
import type { ProductoSchema } from './productoSchema';

export interface CompraProductoSchema {
  producto: ProductoSchema;
  producto_nombre: string;
  producto_imagen?: string | null;
  precio_venta: number;
  unidad_medida?: string | null;
  cantidad?: string | null;
  /** @maxLength 50 */
  estado_compra?: string;
  motivo_no_compra?: string | null;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  precio_de_compra: string;
  ganancia_deseada?: string | null;
}
