/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Compras
 * OpenAPI spec version: 1.0.0
 */
import type { CompraProductoSchema } from './compraProductoSchema';
import type { PedidoProductoCompraSchema } from './pedidoProductoCompraSchema';
import type { PedidoSchema } from './pedidoSchema';

export interface CompraSchema {
  productos?: CompraProductoSchema[];
  pedido: PedidoSchema;
  pedido_productos?: PedidoProductoCompraSchema[];
  id?: number | null;
  creado_por: number;
  negocio: number;
  fecha_creacion: string;
  en_respuesta_a_pedido: number;
  /** @maxLength 50 */
  estado: string;
}
