/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Compras
 * OpenAPI spec version: 1.0.0
 */
import type { CompraSchema } from './compraSchema';

export interface PagedCompraSchema {
  items: CompraSchema[];
  count: number;
}
