/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Compras
 * OpenAPI spec version: 1.0.0
 */
import type { ProductoSchema } from './productoSchema';

export interface PedidoProductoCompraSchema {
  id: number;
  producto: ProductoSchema;
  cantidad_solicitada: number;
  unidad_medida: string;
  estado_compra?: 'comprado' | 'no_comprado' | null;
  motivo_no_compra?: string | null;
}
