/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Compras
 * OpenAPI spec version: 1.0.0
 */
import type { PedidoProductoSchema } from './pedidoProductoSchema';

export interface PedidoSchema {
  productos?: PedidoProductoSchema[];
  id?: number | null;
  creado_por: number;
  negocio: number;
  fecha_creacion: string;
  /** @maxLength 50 */
  estado: string;
}
