/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Compras
 * OpenAPI spec version: 1.0.0
 */

export interface ProductoSchema {
  id?: number | null;
  /** @maxLength 100 */
  nombre: string;
  se_vende_en_unidad_medida?: string | null;
  imagen?: string | null;
}
