/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Usuarios
 * OpenAPI spec version: 1.0.0
 */
import type {
  PagedUsuarioSchema,
  TokenSchema,
  UsuarioAsignarNegocioSchema,
  UsuarioCreateSchema,
  UsuarioLoginSchema,
  UsuarioQuitarNegocioSchema,
  UsuarioSchema,
  UsuarioUpdateSchema,
  UsuariosApiListarUsuariosParams
} from './schemas';

/**
 * 🔒 **Permisos requeridos:** Admin
 * @summary Listar Usuarios
 */
export type usuariosApiListarUsuariosResponse200 = {
  data: PagedUsuarioSchema
  status: 200
}
    
export type usuariosApiListarUsuariosResponseSuccess = (usuariosApiListarUsuariosResponse200) & {
  headers: Headers;
};
;

export type usuariosApiListarUsuariosResponse = (usuariosApiListarUsuariosResponseSuccess)

export const getUsuariosApiListarUsuariosUrl = (params?: UsuariosApiListarUsuariosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/usuarios/listar?${stringifiedParams}` : `/api/usuarios/listar`
}

export const usuariosApiListarUsuarios = async (params?: UsuariosApiListarUsuariosParams, options?: RequestInit): Promise<usuariosApiListarUsuariosResponse> => {
  
  const res = await fetch(getUsuariosApiListarUsuariosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuariosApiListarUsuariosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuariosApiListarUsuariosResponse
}



/**
 * 🔒 **Permisos requeridos:** Admin
 * @summary Obtener Usuario
 */
export type usuariosApiObtenerUsuarioResponse200 = {
  data: UsuarioSchema
  status: 200
}
    
export type usuariosApiObtenerUsuarioResponseSuccess = (usuariosApiObtenerUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuariosApiObtenerUsuarioResponse = (usuariosApiObtenerUsuarioResponseSuccess)

export const getUsuariosApiObtenerUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/obtener/${usuarioId}`
}

export const usuariosApiObtenerUsuario = async (usuarioId: number, options?: RequestInit): Promise<usuariosApiObtenerUsuarioResponse> => {
  
  const res = await fetch(getUsuariosApiObtenerUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuariosApiObtenerUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuariosApiObtenerUsuarioResponse
}



/**
 * @summary Obtener Usuario Actual
 */
export type usuariosApiObtenerUsuarioActualResponse200 = {
  data: UsuarioSchema
  status: 200
}
    
export type usuariosApiObtenerUsuarioActualResponseSuccess = (usuariosApiObtenerUsuarioActualResponse200) & {
  headers: Headers;
};
;

export type usuariosApiObtenerUsuarioActualResponse = (usuariosApiObtenerUsuarioActualResponseSuccess)

export const getUsuariosApiObtenerUsuarioActualUrl = () => {


  

  return `/api/usuarios/me`
}

export const usuariosApiObtenerUsuarioActual = async ( options?: RequestInit): Promise<usuariosApiObtenerUsuarioActualResponse> => {
  
  const res = await fetch(getUsuariosApiObtenerUsuarioActualUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuariosApiObtenerUsuarioActualResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuariosApiObtenerUsuarioActualResponse
}



/**
 * 🔒 **Permisos requeridos:** Admin
 * @summary Register Usuario
 */
export type usuariosApiRegisterUsuarioResponse200 = {
  data: UsuarioSchema
  status: 200
}
    
export type usuariosApiRegisterUsuarioResponseSuccess = (usuariosApiRegisterUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuariosApiRegisterUsuarioResponse = (usuariosApiRegisterUsuarioResponseSuccess)

export const getUsuariosApiRegisterUsuarioUrl = () => {


  

  return `/api/usuarios/register`
}

export const usuariosApiRegisterUsuario = async (usuarioCreateSchema: UsuarioCreateSchema, options?: RequestInit): Promise<usuariosApiRegisterUsuarioResponse> => {
  
  const res = await fetch(getUsuariosApiRegisterUsuarioUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuariosApiRegisterUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuariosApiRegisterUsuarioResponse
}



/**
 * @summary Login Usuario
 */
export type usuariosApiLoginUsuarioResponse200 = {
  data: TokenSchema
  status: 200
}
    
export type usuariosApiLoginUsuarioResponseSuccess = (usuariosApiLoginUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuariosApiLoginUsuarioResponse = (usuariosApiLoginUsuarioResponseSuccess)

export const getUsuariosApiLoginUsuarioUrl = () => {


  

  return `/api/usuarios/login`
}

export const usuariosApiLoginUsuario = async (usuarioLoginSchema: UsuarioLoginSchema, options?: RequestInit): Promise<usuariosApiLoginUsuarioResponse> => {
  
  const res = await fetch(getUsuariosApiLoginUsuarioUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioLoginSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuariosApiLoginUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuariosApiLoginUsuarioResponse
}



/**
 * 🔒 **Permisos requeridos:** Admin
 * @summary Asignar Negocio A Usuario
 */
export type usuariosApiAsignarNegocioAUsuarioResponse200 = {
  data: UsuarioSchema
  status: 200
}
    
export type usuariosApiAsignarNegocioAUsuarioResponseSuccess = (usuariosApiAsignarNegocioAUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuariosApiAsignarNegocioAUsuarioResponse = (usuariosApiAsignarNegocioAUsuarioResponseSuccess)

export const getUsuariosApiAsignarNegocioAUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/asignar_negocio/${usuarioId}`
}

export const usuariosApiAsignarNegocioAUsuario = async (usuarioId: number,
    usuarioAsignarNegocioSchema: UsuarioAsignarNegocioSchema, options?: RequestInit): Promise<usuariosApiAsignarNegocioAUsuarioResponse> => {
  
  const res = await fetch(getUsuariosApiAsignarNegocioAUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioAsignarNegocioSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuariosApiAsignarNegocioAUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuariosApiAsignarNegocioAUsuarioResponse
}



/**
 * 🔒 **Permisos requeridos:** Admin
 * @summary Quitar Negocio De Usuario
 */
export type usuariosApiQuitarNegocioDeUsuarioResponse200 = {
  data: UsuarioSchema
  status: 200
}
    
export type usuariosApiQuitarNegocioDeUsuarioResponseSuccess = (usuariosApiQuitarNegocioDeUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuariosApiQuitarNegocioDeUsuarioResponse = (usuariosApiQuitarNegocioDeUsuarioResponseSuccess)

export const getUsuariosApiQuitarNegocioDeUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/quitar_negocio/${usuarioId}`
}

export const usuariosApiQuitarNegocioDeUsuario = async (usuarioId: number,
    usuarioQuitarNegocioSchema: UsuarioQuitarNegocioSchema, options?: RequestInit): Promise<usuariosApiQuitarNegocioDeUsuarioResponse> => {
  
  const res = await fetch(getUsuariosApiQuitarNegocioDeUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioQuitarNegocioSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuariosApiQuitarNegocioDeUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuariosApiQuitarNegocioDeUsuarioResponse
}



/**
 * 🔒 **Permisos requeridos:** Admin
 * @summary Actualizar Usuario
 */
export type usuariosApiActualizarUsuarioResponse200 = {
  data: UsuarioSchema
  status: 200
}
    
export type usuariosApiActualizarUsuarioResponseSuccess = (usuariosApiActualizarUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuariosApiActualizarUsuarioResponse = (usuariosApiActualizarUsuarioResponseSuccess)

export const getUsuariosApiActualizarUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/actualizar/${usuarioId}`
}

export const usuariosApiActualizarUsuario = async (usuarioId: number,
    usuarioUpdateSchema: UsuarioUpdateSchema, options?: RequestInit): Promise<usuariosApiActualizarUsuarioResponse> => {
  
  const res = await fetch(getUsuariosApiActualizarUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      usuarioUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuariosApiActualizarUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuariosApiActualizarUsuarioResponse
}



/**
 * 🔒 **Permisos requeridos:** Admin
 * @summary Eliminar Usuario
 */
export type usuariosApiEliminarUsuarioResponse200 = {
  data: void
  status: 200
}
    
export type usuariosApiEliminarUsuarioResponseSuccess = (usuariosApiEliminarUsuarioResponse200) & {
  headers: Headers;
};
;

export type usuariosApiEliminarUsuarioResponse = (usuariosApiEliminarUsuarioResponseSuccess)

export const getUsuariosApiEliminarUsuarioUrl = (usuarioId: number,) => {


  

  return `/api/usuarios/eliminar/${usuarioId}`
}

export const usuariosApiEliminarUsuario = async (usuarioId: number, options?: RequestInit): Promise<usuariosApiEliminarUsuarioResponse> => {
  
  const res = await fetch(getUsuariosApiEliminarUsuarioUrl(usuarioId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usuariosApiEliminarUsuarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usuariosApiEliminarUsuarioResponse
}
