/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Productos
 * OpenAPI spec version: 1.0.0
 */
import type { ProductoUpdateSchema } from './productoUpdateSchema';

export type ProductoApiActualizarProductoBody = {
  imagen?: Blob;
  payload: ProductoUpdateSchema;
};
