/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Productos
 * OpenAPI spec version: 1.0.0
 */
import type { ProductoCreateSchema } from './productoCreateSchema';

export type ProductoApiCrearProductoBody = {
  imagen?: Blob;
  payload: ProductoCreateSchema;
};
