/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Productos
 * OpenAPI spec version: 1.0.0
 */

export interface ProductoCreateSchema {
  nombre: string;
  se_vende_en_unidad_medida?: 'kg' | 'unidades' | 'litros' | 'otros' | 'atados' | 'cajas' | 'sacos' | 'bandejas' | 'planchas' | null;
  se_compra_en_unidad_medida?: 'kg' | 'unidades' | 'litros' | 'otros' | 'atados' | 'cajas' | 'sacos' | 'bandejas' | 'planchas' | null;
  factor_division?: number | null;
  precio_compra?: number | null;
  ganancia_porcentaje?: number | null;
}
