/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedidos
 * OpenAPI spec version: 1.0.0
 */

export interface ActualizarProductoPedidoSchema {
  producto_id: number;
  cantidad?: number | null;
  unidad_medida?: 'kg' | 'unidades' | 'litros' | 'otros' | 'atados' | 'cajas' | 'sacos' | 'bandejas' | 'planchas' | null;
}
