/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedidos
 * OpenAPI spec version: 1.0.0
 */
import type { PedidoSchema } from './pedidoSchema';

export interface PagedPedidoSchema {
  items: PedidoSchema[];
  count: number;
}
