/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedidos
 * OpenAPI spec version: 1.0.0
 */

export type PedidoApiListarPedidosCompletadosSinCompraParams = {
busqueda?: string | null;
/**
 * @minimum 1
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
