/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedidos
 * OpenAPI spec version: 1.0.0
 */
import type { ProductoSchema } from './productoSchema';

export interface PedidoProductoSchema {
  producto: ProductoSchema;
  id?: number | null;
  /** @pattern ^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$ */
  cantidad: string;
  /** @maxLength 20 */
  unidad_medida?: string;
}
