/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedidos
 * OpenAPI spec version: 1.0.0
 */

export interface PedidoSimpleSchema {
  cantidad_productos?: number;
  creado_por_nombre: string;
  id?: number | null;
  creado_por: number;
  negocio: number;
  fecha_creacion?: string;
  /** @maxLength 50 */
  estado: string;
}
