/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedidos
 * OpenAPI spec version: 1.0.0
 */
import type {
  ActualizarProductoPedidoSchema,
  AgregarProductoPedidoSchema,
  EliminarProductoPedidoSchema,
  PagedPedidoSchema,
  PagedPedidoSimpleSchema,
  PedidoActualizarFechaSchema,
  PedidoApiListarMisPedidosParams,
  PedidoApiListarPedidosCompletadosParams,
  PedidoApiListarPedidosCompletadosSinCompraParams,
  PedidoApiListarPedidosParams,
  PedidoCreateSchema,
  PedidoProductoSchema,
  PedidoSchema,
  PedidoUpdateSchema
} from './schemas';

/**
 * @summary Listar Pedidos
 */
export type pedidoApiListarPedidosResponse200 = {
  data: PagedPedidoSimpleSchema
  status: 200
}
    
export type pedidoApiListarPedidosResponseSuccess = (pedidoApiListarPedidosResponse200) & {
  headers: Headers;
};
;

export type pedidoApiListarPedidosResponse = (pedidoApiListarPedidosResponseSuccess)

export const getPedidoApiListarPedidosUrl = (params?: PedidoApiListarPedidosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos/listar?${stringifiedParams}` : `/api/pedidos/listar`
}

export const pedidoApiListarPedidos = async (params?: PedidoApiListarPedidosParams, options?: RequestInit): Promise<pedidoApiListarPedidosResponse> => {
  
  const res = await fetch(getPedidoApiListarPedidosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiListarPedidosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiListarPedidosResponse
}



/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Listar Pedidos
 */
export type pedidoApiListarPedidosCompletadosResponse200 = {
  data: PagedPedidoSchema
  status: 200
}
    
export type pedidoApiListarPedidosCompletadosResponseSuccess = (pedidoApiListarPedidosCompletadosResponse200) & {
  headers: Headers;
};
;

export type pedidoApiListarPedidosCompletadosResponse = (pedidoApiListarPedidosCompletadosResponseSuccess)

export const getPedidoApiListarPedidosCompletadosUrl = (params?: PedidoApiListarPedidosCompletadosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos/listar_pedidos_completados?${stringifiedParams}` : `/api/pedidos/listar_pedidos_completados`
}

export const pedidoApiListarPedidosCompletados = async (params?: PedidoApiListarPedidosCompletadosParams, options?: RequestInit): Promise<pedidoApiListarPedidosCompletadosResponse> => {
  
  const res = await fetch(getPedidoApiListarPedidosCompletadosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiListarPedidosCompletadosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiListarPedidosCompletadosResponse
}



/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Listar Pedidos Completados Sin Compra
 */
export type pedidoApiListarPedidosCompletadosSinCompraResponse200 = {
  data: PagedPedidoSchema
  status: 200
}
    
export type pedidoApiListarPedidosCompletadosSinCompraResponseSuccess = (pedidoApiListarPedidosCompletadosSinCompraResponse200) & {
  headers: Headers;
};
;

export type pedidoApiListarPedidosCompletadosSinCompraResponse = (pedidoApiListarPedidosCompletadosSinCompraResponseSuccess)

export const getPedidoApiListarPedidosCompletadosSinCompraUrl = (params?: PedidoApiListarPedidosCompletadosSinCompraParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos/listar_pedidos_completados_sin_compra_asociada?${stringifiedParams}` : `/api/pedidos/listar_pedidos_completados_sin_compra_asociada`
}

export const pedidoApiListarPedidosCompletadosSinCompra = async (params?: PedidoApiListarPedidosCompletadosSinCompraParams, options?: RequestInit): Promise<pedidoApiListarPedidosCompletadosSinCompraResponse> => {
  
  const res = await fetch(getPedidoApiListarPedidosCompletadosSinCompraUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiListarPedidosCompletadosSinCompraResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiListarPedidosCompletadosSinCompraResponse
}



/**
 * @summary Obtener Pedido
 */
export type pedidoApiObtenerPedidoResponse200 = {
  data: PedidoSchema
  status: 200
}
    
export type pedidoApiObtenerPedidoResponseSuccess = (pedidoApiObtenerPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiObtenerPedidoResponse = (pedidoApiObtenerPedidoResponseSuccess)

export const getPedidoApiObtenerPedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/obtener/${pedidoId}`
}

export const pedidoApiObtenerPedido = async (pedidoId: number, options?: RequestInit): Promise<pedidoApiObtenerPedidoResponse> => {
  
  const res = await fetch(getPedidoApiObtenerPedidoUrl(pedidoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiObtenerPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiObtenerPedidoResponse
}



/**
 * 🔒 **Permisos requeridos:** Verdulero, Comprador o Admin
 * @summary Listar Mis Pedidos
 */
export type pedidoApiListarMisPedidosResponse200 = {
  data: PagedPedidoSchema
  status: 200
}
    
export type pedidoApiListarMisPedidosResponseSuccess = (pedidoApiListarMisPedidosResponse200) & {
  headers: Headers;
};
;

export type pedidoApiListarMisPedidosResponse = (pedidoApiListarMisPedidosResponseSuccess)

export const getPedidoApiListarMisPedidosUrl = (params?: PedidoApiListarMisPedidosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos/mis_pedidos?${stringifiedParams}` : `/api/pedidos/mis_pedidos`
}

export const pedidoApiListarMisPedidos = async (params?: PedidoApiListarMisPedidosParams, options?: RequestInit): Promise<pedidoApiListarMisPedidosResponse> => {
  
  const res = await fetch(getPedidoApiListarMisPedidosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiListarMisPedidosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiListarMisPedidosResponse
}



/**
 * 🔒 **Permisos requeridos:** Verdulero, Comprador o Admin
 * @summary Crear Pedido
 */
export type pedidoApiCrearPedidoResponse200 = {
  data: PedidoSchema
  status: 200
}
    
export type pedidoApiCrearPedidoResponseSuccess = (pedidoApiCrearPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiCrearPedidoResponse = (pedidoApiCrearPedidoResponseSuccess)

export const getPedidoApiCrearPedidoUrl = () => {


  

  return `/api/pedidos/crear`
}

export const pedidoApiCrearPedido = async (pedidoCreateSchema: PedidoCreateSchema, options?: RequestInit): Promise<pedidoApiCrearPedidoResponse> => {
  
  const res = await fetch(getPedidoApiCrearPedidoUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiCrearPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiCrearPedidoResponse
}



/**
 * 🔒 **Permisos requeridos:** Verdulero, Comprador o Admin
 * @summary Agregar Producto A Pedido
 */
export type pedidoApiAgregarProductoAPedidoResponse200 = {
  data: PedidoProductoSchema
  status: 200
}
    
export type pedidoApiAgregarProductoAPedidoResponseSuccess = (pedidoApiAgregarProductoAPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiAgregarProductoAPedidoResponse = (pedidoApiAgregarProductoAPedidoResponseSuccess)

export const getPedidoApiAgregarProductoAPedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/agregar_producto/${pedidoId}`
}

export const pedidoApiAgregarProductoAPedido = async (pedidoId: number,
    agregarProductoPedidoSchema: AgregarProductoPedidoSchema, options?: RequestInit): Promise<pedidoApiAgregarProductoAPedidoResponse> => {
  
  const res = await fetch(getPedidoApiAgregarProductoAPedidoUrl(pedidoId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agregarProductoPedidoSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiAgregarProductoAPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiAgregarProductoAPedidoResponse
}



/**
 * 🔒 **Permisos requeridos:** Verdulero, Comprador o Admin
 * @summary Eliminar Producto De Pedido
 */
export type pedidoApiEliminarProductoDePedidoResponse200 = {
  data: void
  status: 200
}
    
export type pedidoApiEliminarProductoDePedidoResponseSuccess = (pedidoApiEliminarProductoDePedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiEliminarProductoDePedidoResponse = (pedidoApiEliminarProductoDePedidoResponseSuccess)

export const getPedidoApiEliminarProductoDePedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/eliminar_producto/${pedidoId}`
}

export const pedidoApiEliminarProductoDePedido = async (pedidoId: number,
    eliminarProductoPedidoSchema: EliminarProductoPedidoSchema, options?: RequestInit): Promise<pedidoApiEliminarProductoDePedidoResponse> => {
  
  const res = await fetch(getPedidoApiEliminarProductoDePedidoUrl(pedidoId),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      eliminarProductoPedidoSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiEliminarProductoDePedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiEliminarProductoDePedidoResponse
}



/**
 * 🔒 **Permisos requeridos:** Verdulero, Comprador o Admin
 * @summary Actualizar Producto En Pedido
 */
export type pedidoApiActualizarProductoEnPedidoResponse200 = {
  data: PedidoProductoSchema
  status: 200
}
    
export type pedidoApiActualizarProductoEnPedidoResponseSuccess = (pedidoApiActualizarProductoEnPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiActualizarProductoEnPedidoResponse = (pedidoApiActualizarProductoEnPedidoResponseSuccess)

export const getPedidoApiActualizarProductoEnPedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/actualizar_producto/${pedidoId}`
}

export const pedidoApiActualizarProductoEnPedido = async (pedidoId: number,
    actualizarProductoPedidoSchema: ActualizarProductoPedidoSchema, options?: RequestInit): Promise<pedidoApiActualizarProductoEnPedidoResponse> => {
  
  const res = await fetch(getPedidoApiActualizarProductoEnPedidoUrl(pedidoId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      actualizarProductoPedidoSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiActualizarProductoEnPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiActualizarProductoEnPedidoResponse
}



/**
 * 🔒 **Permisos requeridos:** Verdulero, Comprador o Admin
 * @summary Cambiar Estado Pedido
 */
export type pedidoApiCambiarEstadoPedidoResponse200 = {
  data: PedidoSchema
  status: 200
}
    
export type pedidoApiCambiarEstadoPedidoResponseSuccess = (pedidoApiCambiarEstadoPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiCambiarEstadoPedidoResponse = (pedidoApiCambiarEstadoPedidoResponseSuccess)

export const getPedidoApiCambiarEstadoPedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/cambiar_estado/${pedidoId}`
}

export const pedidoApiCambiarEstadoPedido = async (pedidoId: number,
    pedidoUpdateSchema: PedidoUpdateSchema, options?: RequestInit): Promise<pedidoApiCambiarEstadoPedidoResponse> => {
  
  const res = await fetch(getPedidoApiCambiarEstadoPedidoUrl(pedidoId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiCambiarEstadoPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiCambiarEstadoPedidoResponse
}



/**
 * 🔒 **Permisos requeridos:** Verdulero, Comprador o Admin
 * @summary Eliminar Pedido
 */
export type pedidoApiEliminarPedidoResponse200 = {
  data: void
  status: 200
}
    
export type pedidoApiEliminarPedidoResponseSuccess = (pedidoApiEliminarPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiEliminarPedidoResponse = (pedidoApiEliminarPedidoResponseSuccess)

export const getPedidoApiEliminarPedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/eliminar/${pedidoId}`
}

export const pedidoApiEliminarPedido = async (pedidoId: number, options?: RequestInit): Promise<pedidoApiEliminarPedidoResponse> => {
  
  const res = await fetch(getPedidoApiEliminarPedidoUrl(pedidoId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiEliminarPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiEliminarPedidoResponse
}



/**
 * 🔒 **Permisos requeridos:** Verdulero, Comprador o Admin
 * @summary Cambiar Fecha Pedido
 */
export type pedidoApiCambiarFechaPedidoResponse200 = {
  data: PedidoSchema
  status: 200
}
    
export type pedidoApiCambiarFechaPedidoResponseSuccess = (pedidoApiCambiarFechaPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoApiCambiarFechaPedidoResponse = (pedidoApiCambiarFechaPedidoResponseSuccess)

export const getPedidoApiCambiarFechaPedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos/cambiar_fecha/${pedidoId}`
}

export const pedidoApiCambiarFechaPedido = async (pedidoId: number,
    pedidoActualizarFechaSchema: PedidoActualizarFechaSchema, options?: RequestInit): Promise<pedidoApiCambiarFechaPedidoResponse> => {
  
  const res = await fetch(getPedidoApiCambiarFechaPedidoUrl(pedidoId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoActualizarFechaSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoApiCambiarFechaPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoApiCambiarFechaPedidoResponse
}
