/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Compras
 * OpenAPI spec version: 1.0.0
 */
import type {
  ActualizarProductoCompraSchema,
  AgregarProductoCompraSchema,
  CompraApiListarComprasParams,
  CompraCreateSchema,
  CompraProductoSchema,
  CompraSchema,
  CompraUpdateSchema,
  EliminarProductoCompraSchema,
  PagedCompraSchema
} from './schemas';

/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Listar Compras
 */
export type compraApiListarComprasResponse200 = {
  data: PagedCompraSchema
  status: 200
}
    
export type compraApiListarComprasResponseSuccess = (compraApiListarComprasResponse200) & {
  headers: Headers;
};
;

export type compraApiListarComprasResponse = (compraApiListarComprasResponseSuccess)

export const getCompraApiListarComprasUrl = (params?: CompraApiListarComprasParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/compras/listar_compras?${stringifiedParams}` : `/api/compras/listar_compras`
}

export const compraApiListarCompras = async (params?: CompraApiListarComprasParams, options?: RequestInit): Promise<compraApiListarComprasResponse> => {
  
  const res = await fetch(getCompraApiListarComprasUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: compraApiListarComprasResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as compraApiListarComprasResponse
}



/**
 * @summary Obtener Compra
 */
export type compraApiObtenerCompraResponse200 = {
  data: CompraSchema
  status: 200
}
    
export type compraApiObtenerCompraResponseSuccess = (compraApiObtenerCompraResponse200) & {
  headers: Headers;
};
;

export type compraApiObtenerCompraResponse = (compraApiObtenerCompraResponseSuccess)

export const getCompraApiObtenerCompraUrl = (compraId: number,) => {


  

  return `/api/compras/obtener/${compraId}`
}

export const compraApiObtenerCompra = async (compraId: number, options?: RequestInit): Promise<compraApiObtenerCompraResponse> => {
  
  const res = await fetch(getCompraApiObtenerCompraUrl(compraId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: compraApiObtenerCompraResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as compraApiObtenerCompraResponse
}



/**
 * @summary Obtener Compra Asociada
 */
export type compraApiObtenerCompraAsociadaResponse200 = {
  data: CompraSchema
  status: 200
}
    
export type compraApiObtenerCompraAsociadaResponseSuccess = (compraApiObtenerCompraAsociadaResponse200) & {
  headers: Headers;
};
;

export type compraApiObtenerCompraAsociadaResponse = (compraApiObtenerCompraAsociadaResponseSuccess)

export const getCompraApiObtenerCompraAsociadaUrl = (pedidoId: number,) => {


  

  return `/api/compras/obtener_pedido_asociado/${pedidoId}`
}

export const compraApiObtenerCompraAsociada = async (pedidoId: number, options?: RequestInit): Promise<compraApiObtenerCompraAsociadaResponse> => {
  
  const res = await fetch(getCompraApiObtenerCompraAsociadaUrl(pedidoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: compraApiObtenerCompraAsociadaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as compraApiObtenerCompraAsociadaResponse
}



/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Crear Compra
 */
export type compraApiCrearCompraResponse200 = {
  data: CompraSchema
  status: 200
}
    
export type compraApiCrearCompraResponseSuccess = (compraApiCrearCompraResponse200) & {
  headers: Headers;
};
;

export type compraApiCrearCompraResponse = (compraApiCrearCompraResponseSuccess)

export const getCompraApiCrearCompraUrl = () => {


  

  return `/api/compras/crear`
}

export const compraApiCrearCompra = async (compraCreateSchema: CompraCreateSchema, options?: RequestInit): Promise<compraApiCrearCompraResponse> => {
  
  const res = await fetch(getCompraApiCrearCompraUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      compraCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: compraApiCrearCompraResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as compraApiCrearCompraResponse
}



/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Agregar Producto A Compra
 */
export type compraApiAgregarProductoACompraResponse200 = {
  data: CompraProductoSchema
  status: 200
}
    
export type compraApiAgregarProductoACompraResponseSuccess = (compraApiAgregarProductoACompraResponse200) & {
  headers: Headers;
};
;

export type compraApiAgregarProductoACompraResponse = (compraApiAgregarProductoACompraResponseSuccess)

export const getCompraApiAgregarProductoACompraUrl = (compraId: number,) => {


  

  return `/api/compras/agregar_producto/${compraId}`
}

export const compraApiAgregarProductoACompra = async (compraId: number,
    agregarProductoCompraSchema: AgregarProductoCompraSchema, options?: RequestInit): Promise<compraApiAgregarProductoACompraResponse> => {
  
  const res = await fetch(getCompraApiAgregarProductoACompraUrl(compraId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      agregarProductoCompraSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: compraApiAgregarProductoACompraResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as compraApiAgregarProductoACompraResponse
}



/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Actualizar Producto De Compra
 */
export type compraApiActualizarProductoDeCompraResponse200 = {
  data: CompraProductoSchema
  status: 200
}
    
export type compraApiActualizarProductoDeCompraResponseSuccess = (compraApiActualizarProductoDeCompraResponse200) & {
  headers: Headers;
};
;

export type compraApiActualizarProductoDeCompraResponse = (compraApiActualizarProductoDeCompraResponseSuccess)

export const getCompraApiActualizarProductoDeCompraUrl = (compraId: number,) => {


  

  return `/api/compras/actualizar_producto/${compraId}`
}

export const compraApiActualizarProductoDeCompra = async (compraId: number,
    actualizarProductoCompraSchema: ActualizarProductoCompraSchema, options?: RequestInit): Promise<compraApiActualizarProductoDeCompraResponse> => {
  
  const res = await fetch(getCompraApiActualizarProductoDeCompraUrl(compraId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      actualizarProductoCompraSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: compraApiActualizarProductoDeCompraResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as compraApiActualizarProductoDeCompraResponse
}



/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Cambiar Estado Compra
 */
export type compraApiCambiarEstadoCompraResponse200 = {
  data: CompraSchema
  status: 200
}
    
export type compraApiCambiarEstadoCompraResponseSuccess = (compraApiCambiarEstadoCompraResponse200) & {
  headers: Headers;
};
;

export type compraApiCambiarEstadoCompraResponse = (compraApiCambiarEstadoCompraResponseSuccess)

export const getCompraApiCambiarEstadoCompraUrl = (compraId: number,) => {


  

  return `/api/compras/cambiar_estado/${compraId}`
}

export const compraApiCambiarEstadoCompra = async (compraId: number,
    compraUpdateSchema: CompraUpdateSchema, options?: RequestInit): Promise<compraApiCambiarEstadoCompraResponse> => {
  
  const res = await fetch(getCompraApiCambiarEstadoCompraUrl(compraId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      compraUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: compraApiCambiarEstadoCompraResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as compraApiCambiarEstadoCompraResponse
}



/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Eliminar Producto De Compra
 */
export type compraApiEliminarProductoDeCompraResponse200 = {
  data: void
  status: 200
}
    
export type compraApiEliminarProductoDeCompraResponseSuccess = (compraApiEliminarProductoDeCompraResponse200) & {
  headers: Headers;
};
;

export type compraApiEliminarProductoDeCompraResponse = (compraApiEliminarProductoDeCompraResponseSuccess)

export const getCompraApiEliminarProductoDeCompraUrl = (compraId: number,) => {


  

  return `/api/compras/eliminar_producto/${compraId}`
}

export const compraApiEliminarProductoDeCompra = async (compraId: number,
    eliminarProductoCompraSchema: EliminarProductoCompraSchema, options?: RequestInit): Promise<compraApiEliminarProductoDeCompraResponse> => {
  
  const res = await fetch(getCompraApiEliminarProductoDeCompraUrl(compraId),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      eliminarProductoCompraSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: compraApiEliminarProductoDeCompraResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as compraApiEliminarProductoDeCompraResponse
}



/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Eliminar Compra
 */
export type compraApiEliminarCompraResponse200 = {
  data: void
  status: 200
}
    
export type compraApiEliminarCompraResponseSuccess = (compraApiEliminarCompraResponse200) & {
  headers: Headers;
};
;

export type compraApiEliminarCompraResponse = (compraApiEliminarCompraResponseSuccess)

export const getCompraApiEliminarCompraUrl = (compraId: number,) => {


  

  return `/api/compras/eliminar/${compraId}`
}

export const compraApiEliminarCompra = async (compraId: number, options?: RequestInit): Promise<compraApiEliminarCompraResponse> => {
  
  const res = await fetch(getCompraApiEliminarCompraUrl(compraId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: compraApiEliminarCompraResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as compraApiEliminarCompraResponse
}
