/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Negocios
 * OpenAPI spec version: 1.0.0
 */
import type {
  NegocioApiListarNegociosParams,
  NegocioCreateSchema,
  NegocioSchema,
  NegocioUpdateSchema,
  PagedNegocioSchema
} from './schemas';

/**
 * @summary Listar Negocios
 */
export type negocioApiListarNegociosResponse200 = {
  data: PagedNegocioSchema
  status: 200
}
    
export type negocioApiListarNegociosResponseSuccess = (negocioApiListarNegociosResponse200) & {
  headers: Headers;
};
;

export type negocioApiListarNegociosResponse = (negocioApiListarNegociosResponseSuccess)

export const getNegocioApiListarNegociosUrl = (params?: NegocioApiListarNegociosParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/negocios/listar?${stringifiedParams}` : `/api/negocios/listar`
}

export const negocioApiListarNegocios = async (params?: NegocioApiListarNegociosParams, options?: RequestInit): Promise<negocioApiListarNegociosResponse> => {
  
  const res = await fetch(getNegocioApiListarNegociosUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: negocioApiListarNegociosResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as negocioApiListarNegociosResponse
}



/**
 * 🔒 **Permisos requeridos:** Admin
 * @summary Crear Negocio
 */
export type negocioApiCrearNegocioResponse200 = {
  data: NegocioSchema
  status: 200
}
    
export type negocioApiCrearNegocioResponseSuccess = (negocioApiCrearNegocioResponse200) & {
  headers: Headers;
};
;

export type negocioApiCrearNegocioResponse = (negocioApiCrearNegocioResponseSuccess)

export const getNegocioApiCrearNegocioUrl = () => {


  

  return `/api/negocios/crear`
}

export const negocioApiCrearNegocio = async (negocioCreateSchema: NegocioCreateSchema, options?: RequestInit): Promise<negocioApiCrearNegocioResponse> => {
  
  const res = await fetch(getNegocioApiCrearNegocioUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      negocioCreateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: negocioApiCrearNegocioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as negocioApiCrearNegocioResponse
}



/**
 * 🔒 **Permisos requeridos:** Admin
 * @summary Actualizar Negocio
 */
export type negocioApiActualizarNegocioResponse200 = {
  data: NegocioSchema
  status: 200
}
    
export type negocioApiActualizarNegocioResponseSuccess = (negocioApiActualizarNegocioResponse200) & {
  headers: Headers;
};
;

export type negocioApiActualizarNegocioResponse = (negocioApiActualizarNegocioResponseSuccess)

export const getNegocioApiActualizarNegocioUrl = (negocioId: number,) => {


  

  return `/api/negocios/actualizar/${negocioId}`
}

export const negocioApiActualizarNegocio = async (negocioId: number,
    negocioUpdateSchema: NegocioUpdateSchema, options?: RequestInit): Promise<negocioApiActualizarNegocioResponse> => {
  
  const res = await fetch(getNegocioApiActualizarNegocioUrl(negocioId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      negocioUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: negocioApiActualizarNegocioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as negocioApiActualizarNegocioResponse
}



/**
 * 🔒 **Permisos requeridos:** Admin
 * @summary Eliminar Negocio
 */
export type negocioApiEliminarNegocioResponse200 = {
  data: void
  status: 200
}
    
export type negocioApiEliminarNegocioResponseSuccess = (negocioApiEliminarNegocioResponse200) & {
  headers: Headers;
};
;

export type negocioApiEliminarNegocioResponse = (negocioApiEliminarNegocioResponseSuccess)

export const getNegocioApiEliminarNegocioUrl = (negocioId: number,) => {


  

  return `/api/negocios/eliminar/${negocioId}`
}

export const negocioApiEliminarNegocio = async (negocioId: number, options?: RequestInit): Promise<negocioApiEliminarNegocioResponse> => {
  
  const res = await fetch(getNegocioApiEliminarNegocioUrl(negocioId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: negocioApiEliminarNegocioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as negocioApiEliminarNegocioResponse
}
