/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Negocios
 * OpenAPI spec version: 1.0.0
 */

export interface NegocioSchema {
  id?: number | null;
  /** @maxLength 100 */
  nombre: string;
  direccion?: string | null;
}
