/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Negocios
 * OpenAPI spec version: 1.0.0
 */
import type { NegocioSchema } from './negocioSchema';

export interface PagedNegocioSchema {
  items: NegocioSchema[];
  count: number;
}
