/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */

export type PedidoDiarioUpdateSchemaEstado = typeof PedidoDiarioUpdateSchemaEstado[keyof typeof PedidoDiarioUpdateSchemaEstado];


export const PedidoDiarioUpdateSchemaEstado = {
  en_proceso: 'en_proceso',
  completado: 'completado',
} as const;
