/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */

export type PedidoDiarioEstadoUpdateSchemaEstadoCompra = typeof PedidoDiarioEstadoUpdateSchemaEstadoCompra[keyof typeof PedidoDiarioEstadoUpdateSchemaEstadoCompra];


export const PedidoDiarioEstadoUpdateSchemaEstadoCompra = {
  comprado: 'comprado',
  no_comprado: 'no_comprado',
} as const;
