/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */

export type PedidosSinCompletarSchemaUrgencia = typeof PedidosSinCompletarSchemaUrgencia[keyof typeof PedidosSinCompletarSchemaUrgencia];


export const PedidosSinCompletarSchemaUrgencia = {
  sin_urgencia: 'sin_urgencia',
  a_tiempo: 'a_tiempo',
  pendiente: 'pendiente',
  critico: 'critico',
} as const;
