/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */

export interface PedidoDiarioCantidadNegocioSchema {
  negocio_id: number;
  negocio_nombre: string;
  cantidad: number;
  unidad_medida?: string | null;
}
