/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */
import type { PedidoDiarioTotalPorUnidadSchema } from './pedidoDiarioTotalPorUnidadSchema';

export interface PedidoDiarioUnidadSchema {
  unidad_pedido?: string | null;
  totales_por_unidad?: PedidoDiarioTotalPorUnidadSchema[];
  estado_compra?: 'comprado' | 'no_comprado' | null;
  precio_compra?: number | null;
  factor_division?: number | null;
  ganancia_aplicada?: number | null;
  motivo_no_compra?: string | null;
}
