/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */
import type { PedidosSinCompletarSchemaUrgencia } from './pedidosSinCompletarSchemaUrgencia';

export interface PedidosSinCompletarSchema {
  fecha: string;
  urgencia: PedidosSinCompletarSchemaUrgencia;
}
