/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */
import type { PedidoDiarioEstadoUpdateSchemaEstadoCompra } from './pedidoDiarioEstadoUpdateSchemaEstadoCompra';

export interface PedidoDiarioEstadoUpdateSchema {
  producto_id: number;
  estado_compra: PedidoDiarioEstadoUpdateSchemaEstadoCompra;
  motivo_no_compra?: string | null;
  precio_compra?: number | null;
  factor_division?: number | null;
  ganancia_aplicada?: number | null;
}
