/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */
import type { PedidoDiarioUpdateSchemaEstado } from './pedidoDiarioUpdateSchemaEstado';

export interface PedidoDiarioUpdateSchema {
  estado: PedidoDiarioUpdateSchemaEstado;
}
