/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */

export interface PedidoDiarioTotalPorUnidadSchema {
  unidad_medida?: string | null;
  cantidad_total: number;
}
