/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */
import type { PedidoDiarioProductoSchema } from './pedidoDiarioProductoSchema';

export interface PedidoDiarioSchema {
  fecha: string;
  estado?: 'en_proceso' | 'completado' | null;
  items?: PedidoDiarioProductoSchema[];
}
