/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */
import type { PedidoDiarioCantidadNegocioSchema } from './pedidoDiarioCantidadNegocioSchema';
import type { PedidoDiarioUnidadSchema } from './pedidoDiarioUnidadSchema';
import type { ProductoSchema } from './productoSchema';

export interface PedidoDiarioProductoSchema {
  producto: ProductoSchema;
  cantidades_por_negocio?: PedidoDiarioCantidadNegocioSchema[];
  total: PedidoDiarioUnidadSchema;
}
