/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */

export interface ProductoSchema {
  precio_venta?: number | null;
  actualizado_recientemente?: boolean | null;
  precio_compra_unitario?: number | null;
  id?: number | null;
  /** @maxLength 100 */
  nombre: string;
  se_vende_en_unidad_medida?: string | null;
  se_pide_en_unidad_medida?: string | null;
  precio_compra?: string | null;
  factor_division?: string | null;
  ganancia_porcentaje?: string | null;
  imagen?: string | null;
  ultima_actualizacion?: string | null;
}
