/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Usuarios
 * OpenAPI spec version: 1.0.0
 */

export type TokenSchemaRol = typeof TokenSchemaRol[keyof typeof TokenSchemaRol];


export const TokenSchemaRol = {
  admin: 'admin',
  verdulero: 'verdulero',
  comprador: 'comprador',
} as const;
