/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Usuarios
 * OpenAPI spec version: 1.0.0
 */
import type { TokenSchemaRol } from './tokenSchemaRol';

export interface TokenSchema {
  nombre: string;
  rol: TokenSchemaRol;
  token: string;
}
