/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Usuarios
 * OpenAPI spec version: 1.0.0
 */
import type { NegocioSchema } from './negocioSchema';

export interface UsuarioSchema {
  negocios?: NegocioSchema[];
  id?: number | null;
  /** @maxLength 100 */
  nombre: string;
  /** @maxLength 50 */
  rol: string;
}
