/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Usuarios
 * OpenAPI spec version: 1.0.0
 */

export interface UsuarioUpdateSchema {
  nombre?: string | null;
  contraseña?: string | null;
  rol?: 'admin' | 'verdulero' | 'comprador' | null;
}
