/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Usuarios
 * OpenAPI spec version: 1.0.0
 */

export type UsuarioCreateSchemaRol = typeof UsuarioCreateSchemaRol[keyof typeof UsuarioCreateSchemaRol];


export const UsuarioCreateSchemaRol = {
  admin: 'admin',
  verdulero: 'verdulero',
  comprador: 'comprador',
} as const;
