/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Usuarios
 * OpenAPI spec version: 1.0.0
 */
import type { UsuarioCreateSchemaRol } from './usuarioCreateSchemaRol';

export interface UsuarioCreateSchema {
  nombre: string;
  contraseña: string;
  rol: UsuarioCreateSchemaRol;
}
