/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * API Pedido Diario
 * OpenAPI spec version: 1.0.0
 */
import type {
  PedidoDiarioApiCambiarEstadoPedidoDiarioParams,
  PedidoDiarioApiDesmarcarPedidoDiarioParams,
  PedidoDiarioApiMarcarPedidoDiarioParams,
  PedidoDiarioApiObtenerPedidoDiarioPorFechaParams,
  PedidoDiarioEstadoUpdateSchema,
  PedidoDiarioSchema,
  PedidoDiarioUpdateSchema,
  PedidosSinCompletarSchema
} from './schemas';

/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Obtener Pedido Diario Por Fecha
 */
export type pedidoDiarioApiObtenerPedidoDiarioPorFechaResponse200 = {
  data: PedidoDiarioSchema
  status: 200
}
    
export type pedidoDiarioApiObtenerPedidoDiarioPorFechaResponseSuccess = (pedidoDiarioApiObtenerPedidoDiarioPorFechaResponse200) & {
  headers: Headers;
};
;

export type pedidoDiarioApiObtenerPedidoDiarioPorFechaResponse = (pedidoDiarioApiObtenerPedidoDiarioPorFechaResponseSuccess)

export const getPedidoDiarioApiObtenerPedidoDiarioPorFechaUrl = (params: PedidoDiarioApiObtenerPedidoDiarioPorFechaParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos_diarios/por_fecha?${stringifiedParams}` : `/api/pedidos_diarios/por_fecha`
}

export const pedidoDiarioApiObtenerPedidoDiarioPorFecha = async (params: PedidoDiarioApiObtenerPedidoDiarioPorFechaParams, options?: RequestInit): Promise<pedidoDiarioApiObtenerPedidoDiarioPorFechaResponse> => {
  
  const res = await fetch(getPedidoDiarioApiObtenerPedidoDiarioPorFechaUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoDiarioApiObtenerPedidoDiarioPorFechaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoDiarioApiObtenerPedidoDiarioPorFechaResponse
}



/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Marcar Pedido Diario
 */
export type pedidoDiarioApiMarcarPedidoDiarioResponse200 = {
  data: void
  status: 200
}
    
export type pedidoDiarioApiMarcarPedidoDiarioResponseSuccess = (pedidoDiarioApiMarcarPedidoDiarioResponse200) & {
  headers: Headers;
};
;

export type pedidoDiarioApiMarcarPedidoDiarioResponse = (pedidoDiarioApiMarcarPedidoDiarioResponseSuccess)

export const getPedidoDiarioApiMarcarPedidoDiarioUrl = (params: PedidoDiarioApiMarcarPedidoDiarioParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos_diarios/marcar?${stringifiedParams}` : `/api/pedidos_diarios/marcar`
}

export const pedidoDiarioApiMarcarPedidoDiario = async (pedidoDiarioEstadoUpdateSchema: PedidoDiarioEstadoUpdateSchema,
    params: PedidoDiarioApiMarcarPedidoDiarioParams, options?: RequestInit): Promise<pedidoDiarioApiMarcarPedidoDiarioResponse> => {
  
  const res = await fetch(getPedidoDiarioApiMarcarPedidoDiarioUrl(params),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoDiarioEstadoUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoDiarioApiMarcarPedidoDiarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoDiarioApiMarcarPedidoDiarioResponse
}



/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Desmarcar Pedido Diario
 */
export type pedidoDiarioApiDesmarcarPedidoDiarioResponse200 = {
  data: void
  status: 200
}
    
export type pedidoDiarioApiDesmarcarPedidoDiarioResponseSuccess = (pedidoDiarioApiDesmarcarPedidoDiarioResponse200) & {
  headers: Headers;
};
;

export type pedidoDiarioApiDesmarcarPedidoDiarioResponse = (pedidoDiarioApiDesmarcarPedidoDiarioResponseSuccess)

export const getPedidoDiarioApiDesmarcarPedidoDiarioUrl = (params: PedidoDiarioApiDesmarcarPedidoDiarioParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos_diarios/desmarcar?${stringifiedParams}` : `/api/pedidos_diarios/desmarcar`
}

export const pedidoDiarioApiDesmarcarPedidoDiario = async (pedidoDiarioEstadoUpdateSchema: PedidoDiarioEstadoUpdateSchema,
    params: PedidoDiarioApiDesmarcarPedidoDiarioParams, options?: RequestInit): Promise<pedidoDiarioApiDesmarcarPedidoDiarioResponse> => {
  
  const res = await fetch(getPedidoDiarioApiDesmarcarPedidoDiarioUrl(params),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoDiarioEstadoUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoDiarioApiDesmarcarPedidoDiarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoDiarioApiDesmarcarPedidoDiarioResponse
}



/**
 * 🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Cambiar Estado Pedido Diario
 */
export type pedidoDiarioApiCambiarEstadoPedidoDiarioResponse200 = {
  data: void
  status: 200
}
    
export type pedidoDiarioApiCambiarEstadoPedidoDiarioResponseSuccess = (pedidoDiarioApiCambiarEstadoPedidoDiarioResponse200) & {
  headers: Headers;
};
;

export type pedidoDiarioApiCambiarEstadoPedidoDiarioResponse = (pedidoDiarioApiCambiarEstadoPedidoDiarioResponseSuccess)

export const getPedidoDiarioApiCambiarEstadoPedidoDiarioUrl = (params: PedidoDiarioApiCambiarEstadoPedidoDiarioParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/pedidos_diarios/cambiar_estado?${stringifiedParams}` : `/api/pedidos_diarios/cambiar_estado`
}

export const pedidoDiarioApiCambiarEstadoPedidoDiario = async (pedidoDiarioUpdateSchema: PedidoDiarioUpdateSchema,
    params: PedidoDiarioApiCambiarEstadoPedidoDiarioParams, options?: RequestInit): Promise<pedidoDiarioApiCambiarEstadoPedidoDiarioResponse> => {
  
  const res = await fetch(getPedidoDiarioApiCambiarEstadoPedidoDiarioUrl(params),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      pedidoDiarioUpdateSchema,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoDiarioApiCambiarEstadoPedidoDiarioResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoDiarioApiCambiarEstadoPedidoDiarioResponse
}



/**
 * 🔒 **Permisos requeridos:** Verdulero, Comprador o Admin
 * @summary Obtener Pedido Diario Por Pedido
 */
export type pedidoDiarioApiObtenerPedidoDiarioPorPedidoResponse200 = {
  data: PedidoDiarioSchema
  status: 200
}
    
export type pedidoDiarioApiObtenerPedidoDiarioPorPedidoResponseSuccess = (pedidoDiarioApiObtenerPedidoDiarioPorPedidoResponse200) & {
  headers: Headers;
};
;

export type pedidoDiarioApiObtenerPedidoDiarioPorPedidoResponse = (pedidoDiarioApiObtenerPedidoDiarioPorPedidoResponseSuccess)

export const getPedidoDiarioApiObtenerPedidoDiarioPorPedidoUrl = (pedidoId: number,) => {


  

  return `/api/pedidos_diarios/por_pedido/${pedidoId}`
}

export const pedidoDiarioApiObtenerPedidoDiarioPorPedido = async (pedidoId: number, options?: RequestInit): Promise<pedidoDiarioApiObtenerPedidoDiarioPorPedidoResponse> => {
  
  const res = await fetch(getPedidoDiarioApiObtenerPedidoDiarioPorPedidoUrl(pedidoId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoDiarioApiObtenerPedidoDiarioPorPedidoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoDiarioApiObtenerPedidoDiarioPorPedidoResponse
}



/**
 * Devuelve la lista de fechas que tienen pedidos (compras) y cuyo pedido diario
    no existe o no está marcado como 'completado'.

🔒 **Permisos requeridos:** Comprador o Admin
 * @summary Obtener Pedidos Diarios Sin Completar
 */
export type pedidoDiarioApiObtenerPedidosDiariosSinCompletarResponse200 = {
  data: PedidosSinCompletarSchema[]
  status: 200
}
    
export type pedidoDiarioApiObtenerPedidosDiariosSinCompletarResponseSuccess = (pedidoDiarioApiObtenerPedidosDiariosSinCompletarResponse200) & {
  headers: Headers;
};
;

export type pedidoDiarioApiObtenerPedidosDiariosSinCompletarResponse = (pedidoDiarioApiObtenerPedidosDiariosSinCompletarResponseSuccess)

export const getPedidoDiarioApiObtenerPedidosDiariosSinCompletarUrl = () => {


  

  return `/api/pedidos_diarios/sin_completar`
}

export const pedidoDiarioApiObtenerPedidosDiariosSinCompletar = async ( options?: RequestInit): Promise<pedidoDiarioApiObtenerPedidosDiariosSinCompletarResponse> => {
  
  const res = await fetch(getPedidoDiarioApiObtenerPedidosDiariosSinCompletarUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: pedidoDiarioApiObtenerPedidosDiariosSinCompletarResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pedidoDiarioApiObtenerPedidosDiariosSinCompletarResponse
}
